# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
# .circleci/config.yml
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
      - checkout
      - restore_cache:
          keys:
            - openwrt-v6
      - run: echo "Build OpenWrt system image"
      - run: ./scripts/feeds update -a
      - run: ./scripts/feeds install -a
      - run: make defconfig
      - run:
          name: Build OpenWrt
          command: make -j$(nproc)
          no_output_timeout: 30m
      - run:
          name: Install gh CLI
          command: |
            sudo apt install -y gh
      - run:
          name: Publish GitHub Release
          command: |
            TAG="openwrt-19.07.10-wr840n-v6"
            echo "$GITHUB_TOKEN" | gh auth login --with-token

            gh release create "$TAG" \
              bin/targets/ramips/mt76x8/*.bin \
              bin/targets/ramips/mt76x8/*.manifest \
              bin/targets/ramips/mt76x8/config.buildinfo \
              --title "OpenWrt 19.07.10 WR840N v6" \
              --notes "Automated build via CircleCI"
      - save_cache:
          key: openwrt-v6
          paths:
            - dl
            - feeds

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  build-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
